services:
  gymworkouttracker.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./src/GymWorkoutTracker.Api:/src/GymWorkoutTracker.Api
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    working_dir: /src/GymWorkoutTracker.Api
    command: dotnet watch run --urls http://+:8080;https://+:8081
    ports:
      - "8080:8080"
      - "8081:8081"